/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class Animales extends javax.swing.JFrame {

    private static DefaultTableModel modelo = new DefaultTableModel();
    //Se crea una tabla (no se muestra) que contiene la información de la tabla de habitats, lo cual permite llamar la información almacenada en la tabla de habitats
    private static DefaultTableModel tablaHabitats = Habitats.getModelo();

    public Animales() {
        initComponents();
        setVisible(false);
        setLocationRelativeTo(null);
        setVisible(true);
        if (modelo.getColumnCount() == 0) {
            modelo.addColumn("Nombre");
            modelo.addColumn("Habitat");
            modelo.addColumn("Especie");
            modelo.addColumn("Sexo");
            this.tabla.setModel(modelo);
            precargarDatos();
        }
        this.tabla.setModel(modelo);
    }
    //Metodo para precargar los datos mediante un bucle for-each, luego se llama al método que inicializa las funcionalidades
    private void precargarDatos() {
        String[][] datos = {
            {"León", "Sabana", "Felino", "Macho"},
            {"Tigre", "Selva", "Felino", "Hembra"},};

        for (String[] fila : datos) {
            modelo.addRow(fila);
        }
    }
    
    //Método que permite llamar la tabla de Animales desde otras clases
    public static DefaultTableModel getModelo() {
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        txtHabitat = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bAñadir = new javax.swing.JButton();
        bModi = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtColumna = new javax.swing.JTextField();
        txtNuevo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 128, 46));
        jPanel1.setForeground(new java.awt.Color(176, 128, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(88, 98, 50));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 249, 224));
        jButton1.setText("INICIO");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 50, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 249, 224));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 249, 224));
        jLabel3.setText("Especie");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 249, 224));
        jLabel4.setText("Habitat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 107, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 249, 224));
        jLabel5.setText("Sexo ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 182, -1, -1));

        txtSexo.setBackground(new java.awt.Color(88, 98, 50));
        txtSexo.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 186, 71, -1));

        txtHabitat.setBackground(new java.awt.Color(88, 98, 50));
        txtHabitat.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 111, 71, -1));

        txtEspecie.setBackground(new java.awt.Color(88, 98, 50));
        txtEspecie.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 145, 71, -1));

        txtNombre.setBackground(new java.awt.Color(88, 98, 50));
        txtNombre.setForeground(new java.awt.Color(254, 249, 224));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 70, 71, -1));

        tabla.setBackground(new java.awt.Color(88, 98, 50));
        tabla.setForeground(new java.awt.Color(254, 249, 224));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 406, 318));

        bAñadir.setBackground(new java.awt.Color(88, 98, 50));
        bAñadir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bAñadir.setForeground(new java.awt.Color(254, 249, 224));
        bAñadir.setText("AÑADIR");
        bAñadir.setBorder(null);
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(bAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 387, 60, 20));

        bModi.setBackground(new java.awt.Color(88, 98, 50));
        bModi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bModi.setForeground(new java.awt.Color(254, 249, 224));
        bModi.setText("MODIFICAR");
        bModi.setBorder(null);
        bModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModiActionPerformed(evt);
            }
        });
        jPanel1.add(bModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 387, 80, 20));

        bEliminar.setBackground(new java.awt.Color(88, 98, 50));
        bEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(254, 249, 224));
        bEliminar.setText("ELIMINAR");
        bEliminar.setBorder(null);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 387, 70, 20));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 249, 224));
        jLabel9.setText("Fila");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 249, 224));
        jLabel10.setText("Columna");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 249, 224));
        jLabel11.setText("Nuevo Dato");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtFila.setBackground(new java.awt.Color(88, 98, 50));
        txtFila.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 71, -1));

        txtColumna.setBackground(new java.awt.Color(88, 98, 50));
        txtColumna.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 71, -1));

        txtNuevo.setBackground(new java.awt.Color(88, 98, 50));
        txtNuevo.setForeground(new java.awt.Color(254, 249, 224));
        jPanel1.add(txtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 71, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 249, 224));
        jLabel6.setText("ANIMALES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel7.setBackground(new java.awt.Color(254, 249, 224));
        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ANIMALES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Para Modificar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame in = new JFrame();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    //Metodo del botón que permite añadir la información
    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        String[] info = new String[4];
        info[0] = txtNombre.getText();
        info[1] = txtHabitat.getText();
        info[2] = txtEspecie.getText();
        info[3] = txtSexo.getText();
        boolean habitatExiste = false;
        for (int i = 0; i < tablaHabitats.getRowCount(); i++) {
            if (txtHabitat.getText().equals(tablaHabitats.getValueAt(i, 0))) {
                habitatExiste = true;
                break;
            }
        }

        if (habitatExiste) {
            modelo.addRow(info);
        } else {
            JOptionPane.showMessageDialog(null, "El hábitat no existe");
            txtNombre.setText("");
            txtHabitat.setText("");
            txtEspecie.setText("");
            txtSexo.setText("");
        }
    }//GEN-LAST:event_bAñadirActionPerformed

    //Metodo del botón que permite eliminar la información
    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int fila = tabla.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "seleccione la fila");
        }
    }//GEN-LAST:event_bEliminarActionPerformed
    //Metodo del botón que permite modificar la información
    private void bModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModiActionPerformed
        try {
            int fila = Integer.parseInt(txtFila.getText());
            int columna = Integer.parseInt(txtColumna.getText());
            modelo.setValueAt(txtNuevo.getText(), fila, columna);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese los datos correctamente.");
        }
    }//GEN-LAST:event_bModiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtColumna;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtFila;
    private javax.swing.JTextField txtHabitat;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevo;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
